# Define keys to be pressed in parallel array with profiles.
# ex. keys=["F1", "F2"]
#     profiles=["profile1", "profile2"]
# This will set profile1 when you press F1 and set profile2 when press F2

title = "GoXLR Streamdeck Emulator"

[server]
GoXLRAddress="ws://localhost:6805/?GoXLRApp"
ClientAddress="ws://localhost:6805/client="

[Hotkeys]
keys=["F12", "CTRL + B"]
profiles=["Desk", "Gae"] 